package cz.libsoft.groceryshop.response;


public enum GroceryShopResponseCode {
    ORDER_CREATED,
    ORDER_NOT_CREATED,
    ORDER_PAID,
    ORDER_NOT_PAID,
    ORDER_CANCELLED,
    ORDER_NOT_CANCELLED,
    PRODUCT_CREATED,
    PRODUCT_NOT_CREATED,
    PRODUCT_UPDATED,
    PRODUCT_NOT_UPDATED,
    PRODUCT_QUANTITY_UPDATED,
    PRODUCT_QUANTITY_NOT_UPDATED,
    PRODUCT_DELETED,
    PRODUCT_NOT_DELETED,
    PRODUCT_NOT_FOUND,
    PRODUCT_NOT_ON_STOCK;
}

